homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 350
  unit_system: metric
  time_zone: Europe/Vienna
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
plant: !include plants.yaml
person: !include persons.yaml

frontend:
  javascript_version: auto

config:

lovelace:
  mode: yaml

api:

system_health:

auth:

updater:

custom_updater:
  track:
    - cards
    - components

discovery:

conversation:

light:

sun:
  elevation: 350

  #device_sun_light_trigger:
  #  light_group: group.main_lights
  #  device_group: group.people
  #  disable_turn_off: 1
        
history:

recorder:
  purge_keep_days: 7
  purge_interval: 1
  exclude:
    entities:
      - sensor.time
      - sensor.internet_time
      - sensor.dark_sky_wind_gust # m/s
      - sensor.dark_sky_wind_speed # m/s
      - sensor.owm_wind_speed # m/s
      - sensor.dark_sky_pressure # mbar
      - sensor.owm_pressure # mbar

logbook:

map:

tts:
  - platform: google_translate
    service_name: google_say

device_tracker:
  - platform: google_maps
    username: !secret google_email
    new_device_defaults:
        track_new_devices: true
        hide_if_away: true
  - platform: nmap_tracker
    hosts: !secret ip_range
    exclude:
      - !secret raspi_ip
    home_interval: 1
    new_device_defaults:
        track_new_devices: true
        hide_if_away: true
  - platform: bluetooth_tracker
 
binary_sensor:
  - platform: workday
    country: AT
    province: ST
  - platform: uptimerobot
    api_key: !secret uptimerobot_api_key
  - platform: apcupsd

weather:
  - platform: openweathermap
    api_key: !secret owm_api_key
  - platform: darksky
    api_key: !secret darksky_api_key
  - platform: zamg

apcupsd:

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_pw
    name: Roobert

shopping_list:

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api_key 
    allowed_chat_ids:
      - !secret chat_id_0
#      - !secret chat_id_1

notify:
  - name: grubFX Notifier
    platform: telegram
    chat_id: !secret chat_id_0

pi_hole:
  host: !secret pihole_host 
  api_key: !secret pihole_api_key

proximity:
  home:
    devices:
      - !secret tracker_0
    tolerance: 50

  cf:
    devices:
      - !secret tracker_0
    tolerance: 50
