title: Home

resources:
  - url: /local/monster-card.js?v=0.2.3
    type: js
  - url: /local/tracker-card.js?v=1.2.6
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: null
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module
  - url: /community_plugin/aftership-card/aftership-card.js
    type: module
  - url: /community_plugin/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
    type: module
  - url: /community_plugin/miflora-card/miflora-card.js
    type: js
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module

views:
  - id: home
    title: Home
    icon: mdi:home
    cards:
      - id: time
        type: entities
        show_header_toggle: false
        title: Date & Time
        entities:
          - sensor.date
          - sensor.time
          - sensor.internet_time
          - binary_sensor.workday_sensor

      - id: devices
        type: custom:monster-card
        card:
          type: glance
          title: Active Devices
          show_state: false
        filter:
          include:
            - domain: device_tracker
            - state: home
          exclude:
            - domain: group
            - entity_id: "*google*"
            - state: not_home
            - attributes:
                source_type: bluetooth

      - type: media-control
        entity: media_player.xiaomi_mi_box_s

      - type: plant-status
        entity: plant.camellia_sinensis

      - id: shopping
        type: vertical-stack
        cards:
          - type: shopping-list
            title: Shopping List

      - id: map
        type: vertical-stack
        cards:
          - type: map
            entities:
              - zone.home
              - zone.cf
              - zone.uni
              - !secret tracker_0

      - id: bathroom  
        type: thermostat
        entity: climate.bathroom_radiator

      - id: roobert
        type: custom:vertical-stack-in-card
        title: Roobert
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: vacuum.roobert
                name: run/pause
                tap_action:
                  action: call-service
                  service: vacuum.start_pause
                  #service_data:
                  #  entity_id: vaccum.roobert
                icon: mdi:play-pause

              - type: entity-button
                entity: vacuum.roobert
                name: stop
                tap_action:
                  action: call-service
                  service: vacuum.stop
                  #service_data:
                  #  entity_id: vacuum.roobert
                icon: mdi:stop

              - type: entity-button
                entity: vacuum.roobert
                name: go home
                tap_action:
                  action: call-service
                  service: vacuum.return_to_base
                  #service_data:
                  #  entity_id: vacuum.roobert
                icon: mdi:home-map-marker

          - type: entities
            entities:
              - entity: sensor.roobert_status
                name: Status
              - entity: sensor.roobert_battery
                name: Battery level

          - type: history-graph
            hours_to_show: 72
            entities:
              - entity: sensor.roobert_battery
                name: Battery level

  #########################################

  - id: lights
    title: Lights
    icon: mdi:lightbulb
    panel: true
    cards:
      - type: custom:layout-card
        layout: auto
        cards:
          - type: custom:layout-card
            layout: horizontal
            column_num: 6
            cards:
              - type: entity-button
                name: Dimmed
                icon: mdi:brightness-6
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.dim_all
                entity: scene.dim_all

              - type: entity-button
                name: Futter
                icon: mdi:silverware-variant
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.futter
                entity: scene.futter

              - type: entity-button
                name: Movie
                icon: mdi:movie
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.movie_time
                entity: scene.movie_time

              - type: entity-button
                name: Night
                icon: mdi:bed-empty
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.nightlight
                entity: scene.nightlight

              - type: entity-button
                name: Puff
                icon: mdi:heart-multiple
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.sexy_time
                entity: scene.sexy_time

              - type: entity-button
                name: All Off
                icon: mdi:lightbulb-off
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.all_off
                entity: scene.all_off

          - type: custom:vertical-stack-in-card
            title: Table
            cards:
              - type: entities
                entities:
                  - type: custom:slider-entity-row
                    entity: light.hue_table_1
                    toggle: true
                    min: 1
                  - type: custom:slider-entity-row
                    entity: light.hue_table_2
                    toggle: true
                    min: 1
              - type: light
                entity: light.table
                name: Table

          - type: custom:vertical-stack-in-card
            title: Couch
            cards:
              - type: entities
                entities:
                  - type: custom:slider-entity-row
                    entity: light.couch_muller_candle
                    name: Couch
                    toggle: true
                    min: 1
              - type: light
                entity: light.couch
                name: Couch

          - type: custom:vertical-stack-in-card
            title: Bedroom
            cards:
              - type: entities
                entities:
                  - type: custom:slider-entity-row
                    entity: light.bedrom_hue
                    toggle: true
                    min: 1
                  - type: custom:slider-entity-row
                    entity: light.bedroom_tradfri_candle
                    toggle: true
                    min: 1
              - type: light
                entity: light.bedroom
                name: Bedroom

  #########################################

  - id: weather
    title: Weather
    icon: mdi:weather-partly-cloudy
    cards:
      - type: custom:weather-card
        entity: weather.dark_sky
        name: DS
        current: true
        details: true
        forecast: true

      - type: custom:weather-card
        entity: weather.openweathermap
        name: OWM
        current: true
        details: true
        forecast: true

      - type: history-graph
        title: Temperature
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.mean_temperature
            name: Combined (ZAMG, DarkSky, OWM)

      - type: history-graph
        title: Humidity
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.mean_humidity
            name: Combined (ZAMG, DarkSky, OWM)

      - type: history-graph
        title: Wind
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.mean_wind_speed
            name: Combined (ZAMG, DarkSky, OWM)

      - type: history-graph
        title: Pressure
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.mean_pressure
            name: Combined (ZAMG, DarkSky, OWM)

      - type: history-graph
        title: Precipitation
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.graz_precipitation
            name: Intensity (ZAMG)
          - entity: sensor.dark_sky_precip_probabilty
            name: Probability (DarkSky)
          - entity: sensor.dark_sky_precip_intensity
            name: Intensity (DarkSky)

      - type: history-graph
        title: Visibility
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.dark_sky_visibility
            name: DarkSky

      - type: history-graph
        title: Dew point
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.mean_dewpoint
            name: Combined (ZAMG & DarkSky)

      - type: history-graph
        title: Particulates
        hours_to_show: 72
        refresh_interval: 10
        entities:
          - entity: sensor.luftdaten_22841_p1
            name: P1 (<10µm)
          - entity: sensor.luftdaten_22841_p2
            name: P2 (<2.5µm)

  #########################################

  - id: system
    title: System
    icon: mdi:chip
    cards:
      - id: plex
        type: custom:monster-card
        card:
          title: Plex
          show_header_toggle: false
        filter:
          include:
            - entity_id: "*plex*"
          exclude:
            - status: "unavailable"

      - id: pihole
        type: custom:monster-card
        card:
          title: PiHole
          show_header_toggle: false
        filter:
          include:
            - entity_id: "*pi_hole*"
            - entity_id: "*pihole*"

      - id: uptime
        type: entities
        title: UptimeRobot
        show_header_toggle: false
        entities:
          - binary_sensor.nas
          - binary_sensor.vserv
          - binary_sensor.raspi

      - id: ups
        type: custom:vertical-stack-in-card
        cards:
          - type: custom:monster-card
            card:
              title: UPS
              show_header_toggle: false
            filter:
              include:
                - entity_id: "*sensor.ups*"
              exclude:
                - entity_id: sensor.ups_battery
                - entity_id: sensor.ups_load

          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.ups_battery
                title: UPS Battery
                severity:
                  red: 0
                  yellow: 50
                  green: 75

              - type: gauge
                entity: sensor.ups_load
                title: UPS Load
                severity:
                  green: 0
                  yellow: 50
                  red: 75

      - id: stats
        type: custom:vertical-stack-in-card
        title: System Stats
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.processor_use
                name: CPU Usage
                severity:
                  green: 0
                  yellow: 50
                  red: 80
              - type: gauge
                entity: sensor.memory_use_percent
                name: Memory Usage
                severity:
                  green: 0
                  yellow: 50
                  red: 80

          - type: history-graph
            hours_to_show: 72
            refresh_interval: 1
            entities:
              - entity: sensor.load_1m
                name: Load1
              - entity: sensor.load_5m
                name: Load5
              - entity: sensor.load_15m
                name: Load15
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.load_1m
                name: load 1
                min: 0
                max: 3
                severity:
                  green: 0
                  yellow: 1
                  red: 2
              - type: gauge
                entity: sensor.load_5m
                name: load 5
                min: 0
                max: 3
                severity:
                  green: 0
                  yellow: 1
                  red: 2
              - type: gauge
                entity: sensor.load_15m
                name: load 15
                min: 0
                max: 3
                severity:
                  green: 0
                  yellow: 1
                  red: 2

          - type: history-graph
            hours_to_show: 72
            refresh_interval: 1
            entities:
              - entity: sensor.temperature_zone0
                name: In
              - entity: sensor.temperature_zone1
                name: Mainboard
              - entity: sensor.temperature_zone2
                name: CPU
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.temperature_zone0
                name: Temp 0
                min: 0
                max: 70
                severity:
                  green: 50
                  yellow: 60
                  red: 70
              - type: gauge
                entity: sensor.temperature_zone1
                name: Temp 1
                min: 0
                max: 70
                severity:
                  green: 50
                  yellow: 60
                  red: 70
              - type: gauge
                entity: sensor.temperature_zone2
                name: Temp 2
                min: 0
                max: 70
                severity:
                  green: 50
                  yellow: 60
                  red: 70

      - type: custom:zigbee2mqtt-networkmap
        entity: sensor.zigbee2mqtt_networkmap
